my/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^congo.html/$',views.trial, name='trial'),
	
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

import my.views

urlpatterns = [
	url(r'^$', my.views.index, name='index'),
	url(r'^my/', include('my.urls')),
    url(r'^admin/', admin.site.urls),
]

my/models.py
from django.db import models

# Create your models here.

class mysite(models.Model):
	name = models.CharField(max_length=100)
	due_date = models.DateTimeField()
	
	def __str__(self):
		return self.name
		
class my(models.Model):
	mysite = models.ForeignKey(mysite)
	name = models.CharField(max_length=100)
	due_date = models.DateTimeField()	
	complete = models.BooleanField(default=False)
	
	def __str__(self):
		return self.name

		

my/forms.py
from django import forms
 
class ContactForm(forms.Form):
	subject = forms.CharField(max_length=30)
	message = forms.CharField(max_length=300)
	sender =forms.EmailField()
	cc_myself =forms.BooleanField(required = False)

	
	

my/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from .models import mysite, my
from .forms import ContactForm

def index(request):
	lists = mysite.objects.all()
	return render(request, 'my/portfolio.html', { 'mysites':lists })

def post_form_upload(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		
		if form.is_valid():
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			sender= form.cleaned_data['sender']
			cc_myself = form.cleaned_data['cc_myself']
			recipients = ['shivamchauhan3596@gmail.com']
			if cc_myself:
				recipients.append(sender)
		send_mail(subject,message,sender,recipients)
		return HttpResponseRedirect('request','my/congo.html')
	else:
		form = ContactForm()
	return render(request ,'my/portfolio.html')
	
def trial(request):
	lists = mysite.objects.all()
	return render(request, 'my/congo.html', { 'mysites':lists })

my/templates/my/congo.html
<p style="font-size:25px;text-align:center;">Thanks for contacting ... I will reply you soon.</p>

my/templates/my/detail.html
<h1>{{ mysite }} </h1>
<ul>
	{% for my in mysite.my_set.all %}
		<li><a href="/my/{{mysite.id}}/my/{{my.id}}">{{my}}</a></li>
	{% endfor %}
</ul>

my/templates/my/index.html
{% if mysites %}
	<ul>
		{% for mysite in mysites %}
			<li><a href="/my/{{mysite.id}}/">{{mysite.name}}</a></li>
		{% endfor %}
	</ul>
{% else %}
		<p>No mysites are available.</p>
{% endif %}		

my/templates/my/mydetail.html
<h1>{{ my }}</h1>

<p>Due date: {{my.due_date}}</p>

<form action="/my/{{mysite.id}}/my/{{my.id}}/update/" method="post">
	{% csrf_token %}
	
	<label form="complete">is complete</label>
	{% if my.complete %}
		<input type="checkbox" name="complete" id="complete" checked />
	{% else %}
		<input type="checkbox" name="complete" id="complete" />
	{% endif %}
	<br><br>
	
	<input type="submit" value="update"/>
	
</form>

my/templates/my/portfolio.html
{% load staticfiles %}
<html>
<head>
<title>Shivam Kumar Chauhan</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{% static 'css/style.css' %}" rel="stylesheet"></link>
<link href="{% static 'css/animate.css' %}" rel="stylesheet" media="all"></link>
<script src="{% static 'js/wow.min.js' %}"></script>
<script>
	 new WOW().init();
</script>
</head>
<body class="bg" >

		<ul class="back" >
			<a href="#academics">
				<li class="lite wow fadeInDown" data-wow-delay="0.5s" >
					<img class="bulb"  src="{% static 'img/study.png' %}"></img>
					<p class="big5 blocks">Academics</p>
				</li>
			</a>

			<a href="#projects">
				<li class="lite wow fadeInDown" data-wow-delay="0.3s">
					<img class="bulb"  src="{% static 'img/cirtificate.png' %}"></img>
					<p class="big5 blocks">Projects</p>
				</li>
			</a>

			<a href="#profile">
				<li class="lite wow fadeInDown" data-wow-delay="0.1s">
					<img class="wow pulse" data-wow-delay="1.0s"  id="dp" src="{% static 'img/profile.jpg' %}"></img>
					<p class="big5 blocks">@shivam3596</p>
				</li>
			</a>

			<a href="#skills">
				<li class="lite wow fadeInDown" data-wow-delay="0.3s">
					<img class="bulb"  src="{% static 'img/skill.png' %}"></img>
					<p class="big5 blocks">Skills</p>
				</li>
			</a>

			<a href="#contact">
				<li class="lite wow fadeInDown" data-wow-delay="0.5s">
					<img class="bulb"  src="{% static 'img/contact.png' %}"></img>
					<p class="big5 blocks">Contact me</p>
				</li>
			</a>
		</ul>

	<div class="profile" id="profile">
		<div class="snow">
			<p class="big2">Shivam Kumar Chauhan</p>
		</div>

		<div class="left-side snow wow fadeInUp">
			<p class="big4" >
				A 20 year old <b class="show">web developer | Tech-enthusiast | Programmer </b>... and a great human being.
				<b class="show">Computer science</b> student at MIET. <b class="show">Coding | exploring world | learning new technologies </b> are my interests.
				<b class="show">Playing PC games, Blogging, </b> ... are things i usually do.<br>
				I love to listen other's ideas & believe in <b class="show">Talk less < work more</b>.
			</p>
			<a href="{% static 'css/shivamcv.pdf' %}" target="_blank"><button class="download">Download CV </button></a>
		</div>
		<div class="right-side wow fadeInUp">
			<p class="big3 snow">Web Developer, Tech-Enthusiast</p>
			<p class="big4 snow" style="text-align:center;">Birth Date - 03.05.1996<br>Mobile : 7830963823</p>
			<p class="big4 snow" style="text-align:center;">Email ID: shivamchauhan3596@gmail.com </p>
		</div>
	</div>

	<div class="bada">
		<center><p class="big3" id="academics">Academics</p></center>
		<div class="academics snow wow fadeInUp" data-wow-delay="0.3s">

		<button class="download year">2013 - 2017</button>
			<p class="big4">B.Tech, Computer Science & Engineering</p>
			<p class="big4">Meerut Institute of Engineering and Technology</p>
			<p class="big4">Activities and Participation -</p>
			<p class="big4">ANIMIET animation, SIEED quiz competition, Mental calisthenics Event </p>
		</div>

		<div class="academics snow wow fadeInUp" data-wow-delay="0.3s">
		<button class="download year">2012 - 2013</button>
			<p class="big4">INTERMEDIATE(10+2)</p>
			<p class="big4">Sarasvati vidhya mandir, Muzaffarnagar</p>
			<p class="big4">83.80% in UP Board	</p>

		</div>
		<div class="academics snow wow fadeInUp " data-wow-delay="0.3s">
		<button class="download year">2010 - 2011</button>
			<p class="big4">HIGH SCHOOL</p>
			<p class="big4">Sarasvati vidhya mandir, Muzaffarnagar</p>
			<p class="big4">73.60% in UP Board	</p>
		</div>
	</div>
	<div class="skills snow" id="skills">
		<p class="big3">Skills</p>
		<img class="myskill" src="{% static 'img/graph.png' %}" width="1000" height="400" alt="skills">
	</div>

	<center><p class="big3" id="projects">Projects</p></center>
	<div class="projects">
	<ul>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/Gesture-opencv" target="_blank">
				<div class="title"> Gesture-opencv</div>
			</a>
			<img class="snapshot" src="{% static 'img/opencv.png' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="http://oldstuff.in/" target="_blank">
				<div class="title"> Oldstuff</div>
			</a>
			<img class="snapshot" src="{% static 'img/oldstuff.jpg' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/bootstrapinfo" target="_blank">
				<div class="title">Bootstrapinfo</div>
			</a>
			<img class="snapshot" src="{% static 'img/bootstrapinfo.jpg' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/Google-chrome-extension" target="_blank">
				<div class="title"> Chrome extension</div>
			</a>
			<img class="snapshot" src="{% static 'img/extension.png' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/portfolio" target="_blank">
				<div class="title">My Portfolio</div>
			</a>
			<img class="snapshot" src="{% static 'img/myportfolio.jpg' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/scrapy-web" target="_blank" >
				<div class="title">Scrapy-web</div>
			</a>
			<img class="snapshot" src="{% static 'img/scrapy.png' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/homeshine" target="_blank" >
				<div class="title">HomeShine | NGO </div>
			</a>
			<img class="snapshot" src="{% static 'img/ngo.png' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/weather_report" target="_blank" >
				<div class="title">Weather Report </div>
			</a>
			<img class="snapshot" src="{% static 'img/weather.png' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/isatoria" target="_blank" >
				<div class="title">Isatoria</div>
			</a>
			<img class="snapshot" src="{% static 'img/isatoria.jpg' %}"></img>
		</li>
		<li class="container snow wow zoomIn" data-wow-delay="0.3s">
			<a href="https://github.com/shivam3596/cv-gen" target="_blank" >
				<div class="title">cv-gen</div>
			</a>
			<img class="snapshot" src="{% static 'img/cvgen.png' %}"></img>
		</li>
	</ul>
	</div>

	<div class="contact" id="contact">
		<p class="big5">Leave a Message...</p><br>
			<form method="POST" action="my/congo.html/">{% csrf_token %}
				<p class="big5"><label for="id_subject">Name</label></p>
					<input id="id_subject" class="form-control" type="text" name="subject" required ></input>
				<p class="big5"><label for="id_sender">Email</label></p>
					<input id="id_sender" class="form-control" type="email" name="sender" ></input>
				<p class="big5"><label for="id_message">Message</label></p>
					<textarea id="id_message" class="message" type="text" rows="5" cols="175" name="message" required></textarea>
				<p class="big5"><label for="id_cc_myself">cc myself</label>
					<input id="id_cc_myself" type="checkbox" name="cc_myself" ></input></p>
				<button type="submit" class="download wow shake" data-wow-delay="0.3s">Submit</button>
			</form>
		<div class="social">
			<ul>
				<a href="https://www.facebook.com/shivam.k.chauhan1" target="_blank"><li class="icon"> <img src="{% static 'img/facebook.png' %}" class="soso"></img></li></a>
				<a href="https://github.com/shivam3596" target="_blank"><li class="icon"> <img src="{% static 'img/Github.png' %}" class="soso"></img></li></a>
				<a href="http://w3chauhan.blogspot.in/" target="_blank"><li class="icon"> <img src="{% static 'img/blog.png' %}" class="soso" ></img></li></a>
				<a href="https://in.linkedin.com/in/shivam-kumar-chauhan-563391a8" target="_blank"><li class="icon"> <img src="{% static 'img/Linked.png' %}" class="soso"></img></li></a>
			</ul>
		</div>
	</div>
	<div class="footer">
		View projects on Github | Read my Blog | @W3chauhan
	</div>
</body>
</html>